# Generated by Django 4.2.5 on 2023-09-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='areas',
            field=models.ManyToManyField(related_name='mentors', to='app.area'),
        ),
    ]
