# Generated by Django 4.2.5 on 2023-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='ocupado',
            field=models.BooleanField(null=True),
        ),
    ]
