# Generated by Django 4.2.5 on 2023-09-23 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_area_mentor_mentor_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='mentor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='username',
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_meetings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
