# Generated by Django 4.2.6 on 2023-10-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
