# Generated by Django 4.2.5 on 2023-10-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_availability_ocupado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='ocupado',
            new_name='is_available',
        ),
    ]
