# Generated by Django 4.2.6 on 2023-10-11 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_availability_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='end',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.availability'),
        ),
    ]
